Should not raise an exception if omits the argument in HotCocoa::Graphics::Image#whitepoint
----
require 'rubygems'
require 'hotcocoa/graphics'
include HotCocoa
include Graphics

img = Image.new "input.png"
img.whitepoint
----
/Library/Frameworks/MacRuby.framework/Versions/0.11/usr/lib/ruby/Gems/1.9.2/gems/hotcocoa-0.6.0/lib/hotcocoa/graphics/image.rb:297:in `whitepoint': undefined method `ish' for #<HotCocoa::Graphics::Color:0x200a608e0 ...> (NoMethodError)
	from /Users/watson/tmp/monochrome.rb:14:in `<main>'